//! Go client generator.
//!
//! Produces a Go module with:
//! - `keyva.go`       — public `Client`, URI-first, with connection pool
//! - `connection.go`  — internal protocol codec
//! - `errors.go`      — Keyva error types
//! - `types.go`       — response structs
//! - `pool.go`        — connection pool
//! - `go.mod`         — module definition

use crate::generator::{GeneratedFile, Generator};
use crate::spec::{CommandDef, ProtocolSpec};
use heck::ToUpperCamelCase;
use std::fmt::Write;

pub struct GoGenerator;

impl Generator for GoGenerator {
    fn language(&self) -> &'static str {
        "Go"
    }

    fn generate(&self, spec: &ProtocolSpec) -> Vec<GeneratedFile> {
        vec![
            gen_connection(spec),
            gen_pool(spec),
            gen_errors(spec),
            gen_types(spec),
            gen_client(spec),
            gen_go_mod(spec),
            gen_readme(spec),
        ]
    }
}

fn go_type(spec: &ProtocolSpec, type_name: &str, optional: bool) -> String {
    let base = match spec.types.get(type_name) {
        Some(_t) => match type_name {
            "keyspace" | "credential_id" | "token" => "string",
            "integer" | "unix_timestamp" => "int64",
            "boolean_flag" => "bool",
            "json_value" => "map[string]any",
            _ => "any",
        },
        None => "any",
    };
    if optional && base != "bool" {
        match base {
            "string" => "string".into(),
            "int64" => "*int64".into(),
            "map[string]any" => "map[string]any".into(),
            _ => format!("*{base}"),
        }
    } else {
        base.into()
    }
}

// ─── connection.go (internal) ────────────────────────────────────────────────

fn gen_connection(spec: &ProtocolSpec) -> GeneratedFile {
    GeneratedFile {
        path: "connection.go".into(),
        content: format!(
            r#"// Internal Keyva protocol codec.
//
// This file is an implementation detail of the Keyva client library.
// Do not use directly — use Client instead.
//
// Auto-generated by keyva-codegen. Do not edit.

package keyva

import (
	"bufio"
	"crypto/tls"
	"fmt"
	"io"
	"net"
	"strconv"
	"time"
)

const defaultPort = {port}

type connection struct {{
	conn   net.Conn
	reader *bufio.Reader
}}

func dial(host string, port int, useTLS bool) (*connection, error) {{
	addr := net.JoinHostPort(host, strconv.Itoa(port))
	var c net.Conn
	var err error

	if useTLS {{
		c, err = tls.DialWithDialer(&net.Dialer{{Timeout: 10 * time.Second}}, "tcp", addr, &tls.Config{{}})
	}} else {{
		c, err = net.DialTimeout("tcp", addr, 10*time.Second)
	}}
	if err != nil {{
		return nil, fmt.Errorf("keyva: connect %s: %w", addr, err)
	}}

	return &connection{{
		conn:   c,
		reader: bufio.NewReaderSize(c, 64*1024),
	}}, nil
}}

func (c *connection) execute(args ...string) (any, error) {{
	// Encode command
	buf := fmt.Sprintf("*%d\r\n", len(args))
	for _, arg := range args {{
		buf += fmt.Sprintf("$%d\r\n%s\r\n", len(arg), arg)
	}}
	if _, err := io.WriteString(c.conn, buf); err != nil {{
		return nil, fmt.Errorf("keyva: write: %w", err)
	}}
	return c.readFrame()
}}

func (c *connection) readFrame() (any, error) {{
	line, err := c.reader.ReadString('\n')
	if err != nil {{
		return nil, fmt.Errorf("keyva: read: %w", err)
	}}
	if len(line) < 3 {{
		return nil, fmt.Errorf("keyva: short response")
	}}
	tag := line[0]
	payload := line[1 : len(line)-2] // strip \r\n

	switch tag {{
	case '+':
		return payload, nil
	case '-':
		return nil, parseError(payload)
	case ':':
		n, err := strconv.ParseInt(payload, 10, 64)
		if err != nil {{
			return nil, fmt.Errorf("keyva: invalid integer: %s", payload)
		}}
		return n, nil
	case '$':
		length, err := strconv.Atoi(payload)
		if err != nil {{
			return nil, fmt.Errorf("keyva: invalid bulk length: %s", payload)
		}}
		if length < 0 {{
			return nil, nil
		}}
		data := make([]byte, length+2)
		if _, err := io.ReadFull(c.reader, data); err != nil {{
			return nil, fmt.Errorf("keyva: bulk read: %w", err)
		}}
		return string(data[:length]), nil
	case '*':
		count, err := strconv.Atoi(payload)
		if err != nil {{
			return nil, fmt.Errorf("keyva: invalid array length: %s", payload)
		}}
		arr := make([]any, count)
		for i := range count {{
			arr[i], err = c.readFrame()
			if err != nil {{
				return nil, err
			}}
		}}
		return arr, nil
	case '%':
		count, err := strconv.Atoi(payload)
		if err != nil {{
			return nil, fmt.Errorf("keyva: invalid map length: %s", payload)
		}}
		m := make(map[string]any, count)
		for range count {{
			key, err := c.readFrame()
			if err != nil {{
				return nil, err
			}}
			val, err := c.readFrame()
			if err != nil {{
				return nil, err
			}}
			m[fmt.Sprint(key)] = val
		}}
		return m, nil
	case '_':
		return nil, nil
	default:
		return nil, fmt.Errorf("keyva: unknown response type: %c", tag)
	}}
}}

func (c *connection) close() error {{
	return c.conn.Close()
}}
"#,
            port = spec.protocol.default_port,
        ),
    }
}

// ─── pool.go ─────────────────────────────────────────────────────────────────

fn gen_pool(_spec: &ProtocolSpec) -> GeneratedFile {
    GeneratedFile {
        path: "pool.go".into(),
        content: r#"// Connection pool for Keyva clients.
//
// Auto-generated by keyva-codegen. Do not edit.

package keyva

import (
	"sync"
)

// PoolConfig controls connection pool behavior.
type PoolConfig struct {
	// Maximum number of idle connections to keep in the pool.
	// Default: 4.
	MaxIdle int

	// Maximum number of total connections (idle + in-use).
	// 0 means unlimited. Default: 0.
	MaxOpen int
}

type pool struct {
	mu      sync.Mutex
	host    string
	port    int
	tls     bool
	auth    string
	idle    []*connection
	open    int
	config  PoolConfig
}

func newPool(host string, port int, useTLS bool, auth string, cfg PoolConfig) *pool {
	if cfg.MaxIdle <= 0 {
		cfg.MaxIdle = 4
	}
	return &pool{
		host:   host,
		port:   port,
		tls:    useTLS,
		auth:   auth,
		config: cfg,
	}
}

func (p *pool) get() (*connection, error) {
	p.mu.Lock()

	// Try to reuse an idle connection
	if len(p.idle) > 0 {
		c := p.idle[len(p.idle)-1]
		p.idle = p.idle[:len(p.idle)-1]
		p.mu.Unlock()
		return c, nil
	}

	// Check max open limit
	if p.config.MaxOpen > 0 && p.open >= p.config.MaxOpen {
		p.mu.Unlock()
		// Block would be better, but keep it simple: create anyway
		// A production pool would use a condition variable here
	}

	p.open++
	p.mu.Unlock()

	c, err := dial(p.host, p.port, p.tls)
	if err != nil {
		p.mu.Lock()
		p.open--
		p.mu.Unlock()
		return nil, err
	}

	if p.auth != "" {
		if _, err := c.execute("AUTH", p.auth); err != nil {
			c.close()
			p.mu.Lock()
			p.open--
			p.mu.Unlock()
			return nil, err
		}
	}

	return c, nil
}

func (p *pool) put(c *connection) {
	p.mu.Lock()
	defer p.mu.Unlock()

	if len(p.idle) < p.config.MaxIdle {
		p.idle = append(p.idle, c)
	} else {
		c.close()
		p.open--
	}
}

func (p *pool) close() {
	p.mu.Lock()
	defer p.mu.Unlock()

	for _, c := range p.idle {
		c.close()
	}
	p.idle = nil
	p.open = 0
}
"#
        .into(),
    }
}

// ─── errors.go ───────────────────────────────────────────────────────────────

fn gen_errors(spec: &ProtocolSpec) -> GeneratedFile {
    let mut out = String::from(
        r#"// Keyva error types.
//
// Auto-generated by keyva-codegen. Do not edit.

package keyva

import (
	"fmt"
	"strings"
)

// KeyvaError represents an error returned by the Keyva server.
type KeyvaError struct {
	// Machine-readable error code (e.g. "NOTFOUND", "DENIED").
	Code string

	// Human-readable error message.
	Message string
}

func (e *KeyvaError) Error() string {
	return fmt.Sprintf("[%s] %s", e.Code, e.Message)
}

func parseError(payload string) *KeyvaError {
	code, message, _ := strings.Cut(payload, " ")
	return &KeyvaError{Code: code, Message: message}
}

// Error code constants.
const (
"#,
    );

    for (code, def) in &spec.error_codes {
        let const_name = format!("Err{}", code.to_upper_camel_case());
        writeln!(out, "\t// {} — {}", const_name, def.description).unwrap();
        writeln!(out, "\t{} = \"{}\"", const_name, code).unwrap();
    }

    out.push_str(")\n\n");
    out.push_str(
        r#"// IsCode reports whether the error has the given code.
func IsCode(err error, code string) bool {
	if ke, ok := err.(*KeyvaError); ok {
		return ke.Code == code
	}
	return false
}
"#,
    );

    GeneratedFile {
        path: "errors.go".into(),
        content: out,
    }
}

// ─── types.go ────────────────────────────────────────────────────────────────

fn gen_types(spec: &ProtocolSpec) -> GeneratedFile {
    let mut out = String::from(
        r#"// Keyva response types.
//
// Auto-generated by keyva-codegen. Do not edit.

package keyva

"#,
    );

    for (cmd_name, cmd) in &spec.commands {
        if cmd.response.is_empty() || cmd.simple_response {
            continue;
        }
        let struct_name = format!("{}Response", cmd_name.to_upper_camel_case());
        writeln!(
            out,
            "// {struct_name} is the response from the {} command.",
            cmd.verb
        )
        .unwrap();
        writeln!(out, "type {struct_name} struct {{").unwrap();
        for f in &cmd.response {
            let field_name = f.name.to_upper_camel_case();
            let field_type = go_type(spec, &f.field_type, f.optional);
            writeln!(out, "\t{field_name} {field_type} // {}", f.description).unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // from_map helper
        writeln!(
            out,
            "func parse{struct_name}(m map[string]any) *{struct_name} {{"
        )
        .unwrap();
        writeln!(out, "\tr := &{struct_name}{{}}").unwrap();
        for f in &cmd.response {
            let field_name = f.name.to_upper_camel_case();
            let go_t = go_type(spec, &f.field_type, false);
            match go_t.as_str() {
                "string" => {
                    writeln!(
                        out,
                        "\tif v, ok := m[\"{}\"].(string); ok {{ r.{field_name} = v }}",
                        f.name
                    )
                    .unwrap();
                }
                "int64" => {
                    if f.optional {
                        writeln!(
                            out,
                            "\tif v, ok := m[\"{}\"].(int64); ok {{ r.{field_name} = &v }}",
                            f.name
                        )
                        .unwrap();
                    } else {
                        writeln!(
                            out,
                            "\tif v, ok := m[\"{}\"].(int64); ok {{ r.{field_name} = v }}",
                            f.name
                        )
                        .unwrap();
                    }
                }
                "map[string]any" => {
                    writeln!(
                        out,
                        "\tif v, ok := m[\"{}\"].(map[string]any); ok {{ r.{field_name} = v }}",
                        f.name
                    )
                    .unwrap();
                }
                _ => {
                    writeln!(out, "\tr.{field_name} = m[\"{}\"]", f.name).unwrap();
                }
            }
        }
        writeln!(out, "\treturn r").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    GeneratedFile {
        path: "types.go".into(),
        content: out,
    }
}

// ─── keyva.go (public client) ────────────────────────────────────────────────

fn gen_client(spec: &ProtocolSpec) -> GeneratedFile {
    let mut out = String::from(
        r#"// Package keyva provides a client for the Keyva credential management server.
//
// Auto-generated by keyva-codegen. Do not edit.
//
// Connect using a Keyva URI:
//
//	client, err := keyva.Connect("keyva://localhost")
//	result, err := client.Issue(ctx, "my-keyspace", &keyva.IssueOptions{TTL: 3600})
//	fmt.Println(result.CredentialID, result.Token)
//	client.Close()
package keyva

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
	"strings"
)

// Client is a Keyva client backed by a connection pool.
type Client struct {
	pool *pool
}

// Connect creates a new Client from a Keyva URI.
//
// Supported URI formats:
//
//	keyva://localhost
//	keyva://localhost:6399
//	keyva+tls://prod.example.com
//	keyva://mytoken@localhost:6399
//	keyva://mytoken@localhost/sessions
//	keyva+tls://tok@host:6399/keys
func Connect(uri string, opts ...PoolConfig) (*Client, error) {
	cfg, err := parseURI(uri)
	if err != nil {
		return nil, err
	}
	var poolCfg PoolConfig
	if len(opts) > 0 {
		poolCfg = opts[0]
	}
	p := newPool(cfg.host, cfg.port, cfg.tls, cfg.authToken, poolCfg)
	// Verify connectivity by getting and returning one connection
	c, err := p.get()
	if err != nil {
		return nil, err
	}
	p.put(c)
	return &Client{pool: p}, nil
}

// Close shuts down the client and all pooled connections.
func (c *Client) Close() {
	c.pool.close()
}

func (c *Client) exec(args ...string) (any, error) {
	conn, err := c.pool.get()
	if err != nil {
		return nil, err
	}
	result, err := conn.execute(args...)
	if err != nil {
		conn.close()
		return nil, err
	}
	c.pool.put(conn)
	return result, nil
}

func (c *Client) execMap(args ...string) (map[string]any, error) {
	result, err := c.exec(args...)
	if err != nil {
		return nil, err
	}
	m, ok := result.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("keyva: expected map response, got %T", result)
	}
	return m, nil
}

type uriConfig struct {
	host      string
	port      int
	tls       bool
	authToken string
	keyspace  string
}

func parseURI(uri string) (*uriConfig, error) {
	cfg := &uriConfig{port: defaultPort}

	switch {
	case strings.HasPrefix(uri, "keyva+tls://"):
		cfg.tls = true
		uri = "keyva://" + uri[len("keyva+tls://"):]
	case strings.HasPrefix(uri, "keyva://"):
		// ok
	default:
		return nil, fmt.Errorf("keyva: invalid URI scheme (expected keyva:// or keyva+tls://): %s", uri)
	}

	u, err := url.Parse(uri)
	if err != nil {
		return nil, fmt.Errorf("keyva: invalid URI: %w", err)
	}

	cfg.host = u.Hostname()
	if cfg.host == "" {
		cfg.host = "localhost"
	}

	if p := u.Port(); p != "" {
		if n, err := strconv.Atoi(p); err == nil {
			cfg.port = n
		}
	}

	if u.User != nil {
		cfg.authToken = u.User.Username()
	}

	cfg.keyspace = strings.TrimPrefix(u.Path, "/")

	return cfg, nil
}
"#,
    );

    // Generate methods
    for (cmd_name, cmd) in &spec.commands {
        writeln!(out).unwrap();
        gen_go_method(&mut out, spec, cmd_name, cmd);
    }

    GeneratedFile {
        path: "keyva.go".into(),
        content: out,
    }
}

fn gen_go_method(out: &mut String, _spec: &ProtocolSpec, cmd_name: &str, cmd: &CommandDef) {
    if cmd.streaming {
        writeln!(
            out,
            "// Subscribe is not yet supported in the Go client (requires streaming)."
        )
        .unwrap();
        return;
    }

    let method_name = cmd_name.to_upper_camel_case();
    let positional = cmd.positional_params();
    let named = cmd.named_params();

    let has_options = !named.is_empty();
    let has_response = !cmd.response.is_empty() && !cmd.simple_response;
    let response_type = format!("{}Response", cmd_name.to_upper_camel_case());

    // Generate options struct if needed
    if has_options {
        let opts_name = format!("{method_name}Options");
        writeln!(
            out,
            "// {opts_name} are optional parameters for {method_name}."
        )
        .unwrap();
        writeln!(out, "type {opts_name} struct {{").unwrap();
        for p in &named {
            let field_name = p.name.to_upper_camel_case();
            if p.param_type == "boolean_flag" {
                writeln!(out, "\t{field_name} bool").unwrap();
            } else if p.param_type == "json_value" {
                writeln!(out, "\t{field_name} map[string]any").unwrap();
            } else if p.variadic {
                writeln!(out, "\t{field_name} []string").unwrap();
            } else if p.param_type == "integer" {
                writeln!(out, "\t{field_name} int64").unwrap();
            } else {
                writeln!(out, "\t{field_name} string").unwrap();
            }
        }
        writeln!(out, "}}\n").unwrap();
    }

    // Method signature
    writeln!(out, "// {method_name} — {}", cmd.description).unwrap();

    let mut params: Vec<String> = Vec::new();
    for p in &positional {
        params.push(format!("{} string", p.name));
    }
    if has_options {
        params.push(format!("opts *{method_name}Options"));
    }

    let return_sig = if has_response {
        format!("(*{response_type}, error)")
    } else {
        "error".into()
    };

    writeln!(
        out,
        "func (c *Client) {method_name}({}) {return_sig} {{",
        params.join(", "),
    )
    .unwrap();

    // Build args
    writeln!(out, "\targs := []string{{").unwrap();
    if let Some(sub) = &cmd.subcommand {
        writeln!(out, "\t\t\"{}\", \"{}\",", cmd.verb, sub).unwrap();
    } else {
        writeln!(out, "\t\t\"{}\",", cmd.verb).unwrap();
    }
    for p in &positional {
        if p.required {
            writeln!(out, "\t\t{},", p.name).unwrap();
        }
    }
    writeln!(out, "\t}}").unwrap();

    // Optional positional (like health's optional keyspace)
    for p in &positional {
        if !p.required {
            writeln!(out, "\tif {} != \"\" {{", p.name).unwrap();
            writeln!(out, "\t\targs = append(args, {})", p.name).unwrap();
            writeln!(out, "\t}}").unwrap();
        }
    }

    // Named params from options
    if has_options {
        writeln!(out, "\tif opts != nil {{").unwrap();
        for p in &named {
            let field_name = p.name.to_upper_camel_case();
            let key = p.key.as_deref().unwrap();
            if p.param_type == "boolean_flag" {
                writeln!(out, "\t\tif opts.{field_name} {{").unwrap();
                writeln!(out, "\t\t\targs = append(args, \"{key}\")").unwrap();
                writeln!(out, "\t\t}}").unwrap();
            } else if p.param_type == "json_value" {
                writeln!(out, "\t\tif opts.{field_name} != nil {{").unwrap();
                writeln!(out, "\t\t\tb, _ := json.Marshal(opts.{field_name})").unwrap();
                writeln!(out, "\t\t\targs = append(args, \"{key}\", string(b))").unwrap();
                writeln!(out, "\t\t}}").unwrap();
            } else if p.variadic {
                writeln!(out, "\t\tif len(opts.{field_name}) > 0 {{").unwrap();
                writeln!(out, "\t\t\targs = append(args, \"{key}\")").unwrap();
                writeln!(out, "\t\t\targs = append(args, opts.{field_name}...)").unwrap();
                writeln!(out, "\t\t}}").unwrap();
            } else if p.param_type == "integer" {
                writeln!(out, "\t\tif opts.{field_name} != 0 {{").unwrap();
                writeln!(
                    out,
                    "\t\t\targs = append(args, \"{key}\", strconv.FormatInt(opts.{field_name}, 10))"
                )
                .unwrap();
                writeln!(out, "\t\t}}").unwrap();
            } else {
                writeln!(out, "\t\tif opts.{field_name} != \"\" {{").unwrap();
                writeln!(
                    out,
                    "\t\t\targs = append(args, \"{key}\", opts.{field_name})"
                )
                .unwrap();
                writeln!(out, "\t\t}}").unwrap();
            }
        }
        writeln!(out, "\t}}").unwrap();
    }

    // Execute
    if has_response {
        writeln!(out, "\tm, err := c.execMap(args...)").unwrap();
        writeln!(out, "\tif err != nil {{").unwrap();
        writeln!(out, "\t\treturn nil, err").unwrap();
        writeln!(out, "\t}}").unwrap();
        writeln!(out, "\treturn parse{response_type}(m), nil").unwrap();
    } else {
        writeln!(out, "\t_, err := c.exec(args...)").unwrap();
        writeln!(out, "\treturn err").unwrap();
    }

    writeln!(out, "}}").unwrap();
}

fn gen_go_mod(_spec: &ProtocolSpec) -> GeneratedFile {
    GeneratedFile {
        path: "go.mod".into(),
        content: "module github.com/keyva-io/keyva-go\n\ngo 1.22\n".into(),
    }
}

fn gen_readme(spec: &ProtocolSpec) -> GeneratedFile {
    let mut cmds = String::new();
    for (cmd_name, cmd) in &spec.commands {
        if cmd.streaming {
            continue;
        }
        let method = cmd_name.to_upper_camel_case();
        cmds.push_str(&format!("- `client.{method}(...)` — {}\n", cmd.description));
    }

    GeneratedFile {
        path: "README.md".into(),
        content: format!(
            r#"# Keyva Go Client

Go client for the [Keyva](https://github.com/keyva-io/keyva) credential management server.

## Install

```bash
go get github.com/keyva-io/keyva-go
```

## Quick Start

```go
package main

import (
    "fmt"
    "log"

    keyva "github.com/keyva-io/keyva-go"
)

func main() {{
    client, err := keyva.Connect("keyva://localhost")
    if err != nil {{
        log.Fatal(err)
    }}
    defer client.Close()

    // Issue a credential
    result, err := client.Issue("my-keyspace", &keyva.IssueOptions{{Ttl: 3600}})
    if err != nil {{
        log.Fatal(err)
    }}
    fmt.Println(result.CredentialId, result.Token)

    // Verify it
    verified, err := client.Verify("my-keyspace", result.Token, nil)
    if err != nil {{
        log.Fatal(err)
    }}
    fmt.Println(verified.State) // "active"
}}
```

## Connection URI

```
keyva://[token@]host[:port][/keyspace]
keyva+tls://[token@]host[:port][/keyspace]
```

Examples:
- `keyva://localhost` — plain TCP, default port {port}
- `keyva+tls://prod.example.com` — TLS
- `keyva://mytoken@localhost:6399/sessions` — auth + keyspace

## Connection Pool

The client maintains an internal connection pool. Tune it at connect time:

```go
client, err := keyva.Connect("keyva://localhost", keyva.PoolConfig{{
    MaxIdle: 8,
    MaxOpen: 32,
}})
```

## Commands

{cmds}

## Auto-generated

This client was generated by `keyva-codegen` from `protocol.toml`.
"#,
            port = spec.protocol.default_port,
            cmds = cmds,
        ),
    }
}
